FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["order-service/order-service.csproj", "order-service/"]
COPY ["shared/shared.csproj", "shared/"]
RUN dotnet restore "order-service/order-service.csproj"
COPY . .
WORKDIR "/src/order-service"
RUN dotnet build "order-service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "order-service.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "order-service.dll"]
