FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["payment-service/payment-service.csproj", "payment-service/"]
COPY ["shared/shared.csproj", "shared/"]
RUN dotnet restore "payment-service/payment-service.csproj"
COPY . .
WORKDIR "/src/payment-service"
RUN dotnet build "payment-service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "payment-service.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "payment-service.dll"]
