syntax = "proto3";
option csharp_namespace = "PaymentProto";

package payment;

service PaymentService {
  rpc CreatePayment (CreatePaymentRequest) returns (CreatePaymentResponse);
  rpc CapturePayment (CapturePaymentRequest) returns (CapturePaymentResponse);
}

message CreatePaymentRequest {
  int64 amount = 1;
  string returnUrl = 2;
  string cancelUrl = 3;
}

message CreatePaymentResponse {
  string paymentId = 1;
  string approvalUrl = 2;
  string status = 3;
}

message CapturePaymentRequest {
  string token = 1;
}


message CapturePaymentResponse {
  string token = 1;
  string status = 2;
}

